CREATE DATABASE UserManagementQuiz;

USE UserManagementQuiz;


CREATE TABLE Groups (
	Id INT PRIMARY KEY IDENTITY,
	Name VARCHAR(100) NOT NULL,
);

CREATE TABLE Users (
	Id INT PRIMARY KEY IDENTITY,
	FirstName VARCHAR(100) NOT NULL,
	LastName VARCHAR(100) NOT NULL,
	Email VARCHAR(150) NOT NULL
);

CREATE TABLE GroupUsers (
	GroupId INT,
	UserId INT,

	CONSTRAINT GroupUsers_PK PRIMARY KEY(GroupId, UserId),
	CONSTRAINT GroupId_FK FOREIGN KEY(GroupId) REFERENCES Groups(Id),
	CONSTRAINT UserId_FK FOREIGN KEY(UserId) REFERENCES Users(Id)
);